from llm.utils.prompts import (
    FIXIE_PERSONA_PROMPT, BYTEFIX_PERSONA_PROMPT, 
    ROUTERX_PERSONA_PROMPT, SENTINEL_PERSONA_PROMPT, HYPERNET_PERSONA_PROMPT, 
    PROFESSOR_PING_PERSONA_PROMPT
)

PERSONA_MAPPING = {
    "fixie": FIXIE_PERSONA_PROMPT,
    "bytefix": BYTEFIX_PERSONA_PROMPT,
    "routerx": ROUTERX_PERSONA_PROMPT,
    "sentinel": SENTINEL_PERSONA_PROMPT,
    "hypernet": HYPERNET_PERSONA_PROMPT,
    "professor_ping": PROFESSOR_PING_PERSONA_PROMPT
}