version: "3.13.3"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  network-chatbot-agent:
    build:
      context: .
    container_name: network-chatbot-agent
    ports:
      - "8501:8501"
    depends_on:
      ollama:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Ollama service is ready' &&
        echo 'Pulling models...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"gemma3:12b-it-q4_K_M\"}' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"gemma3\"}' &&
        echo 'Starting app...' &&
        python -m streamlit run app.py
      "
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=http://ollama:11434

volumes:
  ollama: